spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/scott?useSSL=false&allowPublicKeyRetrieval=true
        #driver-class-name: oracle.jdbc.OracleDriver
        #url: jdbc:oracle:thin:@localhost:1521:scott
        username: scott
        password: 'tiger'
        tomcat:
            removeAbandoned: true
            removeAbandonedTimeout: 120
            logAbandoned: true
            initialSize: 2
            maxActive: 8
            maxIdle: 4
            minIdle: 2
            maxWait: 10000
            validationQuery: select 1
            testOnBorrow: true
            testOnConnect: true
            testWhileIdle: true

server:
    address: 127.0.0.1
    port: 8080

mybatis:
    type-handlers-package: com.example.demo.config
    mapper-locations: classpath:mapper/**/*Mapper.xml
    configuration:
        lazyLoadingEnabled: true
        aggressiveLazyLoading: false
        mapUnderscoreToCamelCase: true
