FROM gradle:8.6.0-jdk17-alpine as builder
WORKDIR /build

COPY build.gradle settings.gradle /build/
RUN gradle build -x test --parallel --continue > /dev/null 2>&1 || true

COPY . /build
RUN gradle build -x test --parallel

FROM eclipse-temurin:17-jdk-alpine
RUN apk --no-cache add curl
WORKDIR /app

COPY --from=builder /build/build/libs/demo-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8080

USER nobody
ENTRYPOINT ["java", "-jar", "app.jar"]