version: "3.8"
services:
  mysql:
    image: mysql:latest
    container_name: mysql-demo
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: scott
    restart: always
    init: true
    networks:
      default: {}
    ports:
      - "3306:3306"
  cubrid:
    image: cubrid/cubrid:latest
    container_name: cubrid-demo
    environment:
      CUBRID_DB: scott
      CUBRID_PASSWORD: tiger
    restart: always
    init: true
    networks:
      default: {}
    ports:
      - "30000:30000"
  was:
    image: spring-boot-examples/demo:0.5.0
    container_name: spring-boot-demo
    restart: always
    init: true
    networks:
      default: {}
    ports:
      - "8080:8080"
    depends_on:
     - mysql
     - cubrid
networks:
  default:
    driver: bridge