FROM eclipse-temurin:17-jdk-alpine as builder
WORKDIR /app
CMD ["./gradlew", "clean", "build"]
ARG JAR_FILE_PATH=build/libs/*.jar
COPY ${JAR_FILE_PATH} app.jar
RUN apk --no-cache add curl
ENTRYPOINT ["java", "-jar", "app.jar"]