spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/scott?useSSL=false&allowPublicKeyRetrieval=true
        #driver-class-name: oracle.jdbc.OracleDriver
        #url: jdbc:oracle:thin:@localhost:1521:scott
        username: scott
        password: 'tiger'
        tomcat:
            removeAbandoned: true
            removeAbandonedTimeout: 120
            logAbandoned: true
            initialSize: 2
            maxActive: 8
            maxIdle: 4
            minIdle: 2
            maxWait: 10000
            validationQuery: select 1
            testOnBorrow: true
            testOnConnect: true
            testWhileIdle: true

mybatis:
    type-handlers-package: com.example.demo.config
    mapper-locations: classpath:mapper/**/*Mapper.xml
    configuration:
        lazyLoadingEnabled: true
        aggressiveLazyLoading: false
        mapUnderscoreToCamelCase: true

cloud:
  aws:
    credentials:
      access-key: AKIAUFNO2TNFWOVMD6XX
      secret-key: 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
    region:
      static: ap-northeast-2
    stack:
      auto: false
    sqs:
      queue:
        name: linq-dev-ap2-sqs-mq-01
        url: https://sqs.ap-northeast-2.amazonaws.com/286518844235/linq-dev-ap2-sqs-mq-01